# --- STAGE 1: Build ---
FROM gradle:8.4-jdk21 AS builder

WORKDIR /app

# Copy hanya file gradle
COPY apps/service-management/build.gradle.kts ./build.gradle.kts
COPY apps/service-management/gradle.properties ./gradle.properties
COPY apps/service-management/settings.gradle.kts ./settings.gradle.kts
COPY gradle/ ./gradle/

# Copy source
COPY apps/service-management/src/ ./src/

# Build dengan Gradle
RUN gradle build -x test

# --- STAGE 2: Run ---
FROM openjdk:21-slim

WORKDIR /app

# Copy jar dari build stage
COPY --from=builder /app/build/libs/*.jar ./app.jar

# Expose port
EXPOSE 8001

# Jalankan aplikasi
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
